on: [push]

jobs:
  build_linux:
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@v6
    - run: git submodule update --init --recursive
    - run: make build FLAGS_EXTRA=-fanalyzer
  build_linux_no_assembly:
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@v6
    - run: git submodule update --init --recursive
    - run: make build FLAGS_EXTRA="-fanalyzer -DNO_ASSEMBLY"
  test_linux:
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@v6
    - run: git submodule update --init --recursive
    - run: make test
  test_linux_no_assembly:
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@v6
    - run: git submodule update --init --recursive
    - run: make test FLAGS_EXTRA=-DNO_ASSEMBLY
  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - run: git submodule update --init --recursive
    - run: make build
  build_mac_no_assembly:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - run: git submodule update --init --recursive
    - run: make build FLAGS_EXTRA=-DNO_ASSEMBLY
  test_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - run: git submodule update --init --recursive
    - run: make test
  test_mac_no_assembly:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - run: git submodule update --init --recursive
    - run: make test FLAGS_EXTRA=-DNO_ASSEMBLY